/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists/index'
import { Route as MacrosIndexRouteImport } from './routes/macros/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as DevicesDeviceIdRouteImport } from './routes/devices/$deviceId'
import { Route as DevicesDeviceIdMemoryRouteImport } from './routes/devices_.$deviceId.memory'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const MacrosIndexRoute = MacrosIndexRouteImport.update({
  id: '/macros/',
  path: '/macros/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdRoute = DevicesDeviceIdRouteImport.update({
  id: '/devices/$deviceId',
  path: '/devices/$deviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesDeviceIdMemoryRoute = DevicesDeviceIdMemoryRouteImport.update({
  id: '/devices_/$deviceId/memory',
  path: '/devices/$deviceId/memory',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/macros/': typeof MacrosIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/devices/$deviceId/memory': typeof DevicesDeviceIdMemoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/collections': typeof CollectionsIndexRoute
  '/macros': typeof MacrosIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
  '/devices/$deviceId/memory': typeof DevicesDeviceIdMemoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/devices/$deviceId': typeof DevicesDeviceIdRoute
  '/collections/': typeof CollectionsIndexRoute
  '/macros/': typeof MacrosIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
  '/devices_/$deviceId/memory': typeof DevicesDeviceIdMemoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/devices/$deviceId'
    | '/collections/'
    | '/macros/'
    | '/playlists/'
    | '/devices/$deviceId/memory'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/devices/$deviceId'
    | '/collections'
    | '/macros'
    | '/playlists'
    | '/devices/$deviceId/memory'
  id:
    | '__root__'
    | '/'
    | '/devices/$deviceId'
    | '/collections/'
    | '/macros/'
    | '/playlists/'
    | '/devices_/$deviceId/memory'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevicesDeviceIdRoute: typeof DevicesDeviceIdRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  MacrosIndexRoute: typeof MacrosIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
  DevicesDeviceIdMemoryRoute: typeof DevicesDeviceIdMemoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/macros/': {
      id: '/macros/'
      path: '/macros'
      fullPath: '/macros/'
      preLoaderRoute: typeof MacrosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices/$deviceId': {
      id: '/devices/$deviceId'
      path: '/devices/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof DevicesDeviceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices_/$deviceId/memory': {
      id: '/devices_/$deviceId/memory'
      path: '/devices/$deviceId/memory'
      fullPath: '/devices/$deviceId/memory'
      preLoaderRoute: typeof DevicesDeviceIdMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevicesDeviceIdRoute: DevicesDeviceIdRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  MacrosIndexRoute: MacrosIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
  DevicesDeviceIdMemoryRoute: DevicesDeviceIdMemoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
